### ISSUE TITLE
某些文字有颜色，但是下载的文档没有而且部分图片缺失

### ISSUE THREAD

**Issue by 233lol** [BoyInTheSun/wks#10]
某些文字有颜色，但是下载的文档没有而且部分图片缺失

**Comment by BoyInTheSun** [comment]
请提供文档链接。
由于原始数据格式未知，所有参数意义只能靠猜，但没办法找到包含所有数据格式的文档。

**Comment by 233lol** [comment]
> 请提供文档链接。 由于原始数据格式未知，所有参数意义只能靠猜，但没办法找到包含所有数据格式的文档。

https://wenku.baidu.com/view/a4754f19031ca300a6c30c22590102020740f2e8.html
