### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by kenpocket** [BoyInTheSun/wks#13]
line 265, in <module>
    save_pdf(temp_dir, pagenums[i])
   line 84, in save_pdf
    if item['ps'].get('_drop') and item['ps'].get('_drop') == 1:
AttributeError: 'NoneType' object has no attribute 'get'

python main.py https://wenku.baidu.com/view/c79033aed3d233d4b14e852458fb770bf78a3b7a.html

**Comment by BoyInTheSun** [comment]
I solved the problem by commit 377f5e7143536078916cacc78ee941e8a5459e2d.
please run `git pull` to get the latest code
