### ISSUE TITLE
依赖包中的gzip包不存在

### ISSUE THREAD

**Issue by 150481878** [BoyInTheSun/wks#2]
错误提示为：
D:\wks>pip install gzip
ERROR: Could not find a version that satisfies the requirement gzip (from versions: none)
ERROR: No matching distribution found for gzip

在Pypi官网上搜素后未找到gzip包。

**Comment by BoyInTheSun** [comment]
gzip库是Python自带库，应该可以直接import。出现在requirements.txt是疏忽了
