### ISSUE TITLE
提交修复bug的建议

### ISSUE THREAD

**Issue by bean0283** [BoyInTheSun/wks#20]
你好，https://wenku.baidu.com/aggs/70d5ba1ffc4ffe473368abbb该网址下载失败，进行分析是空格造成的异常，现提供我的建议，望作者有更好的方式可以提供交流
原代码title = re.search(r'<title>(.*) - 百度文库</title>', html).group(1)
但是我们可以观察返回的html可以发现“-百度文库”之间是没有空格的，这里就会报异常而结束下载
本人的处理方式比较粗暴title = re.search(r'<title>(.*)-百度文库</title>', html.replace(" ","")).group(1)
直接去所有空格解决了

**Comment by bean0283** [comment]
上面代码里的   星号   被系统吃了，请注意

**Comment by BoyInTheSun** [comment]
感谢！马上处理该问题。
顺便一提，这里是遵从markdown语法的，星号等需要加转义字符才能正常显示，或者将代码用代码块展示。

**Comment by zzhhxx** [comment]
捕捉，麻烦你在52pojie发布的软件(https://www.52pojie.cn/thread-1690024-1-1.html)加上作者的github连接，谢谢

**Comment by BoyInTheSun** [comment]
> 捕捉，麻烦你在52pojie上加上作者的github连接，谢谢 https://www.52pojie.cn/thread-1690024-1-1.html

我前段时间关注到了该作者的二次开发。他人是否遵从开源协议以及是否引用本项目并非我所能左右的。我会在未来一段时间继续维护该项目，但不会做可视化，也不会发布在国内论坛。
感谢！

**Comment by zzhhxx** [comment]
> 我前段时间关注到了该作者的二次开发。他人是否遵从开源协议以及是否引用本项目并非我所能左右的。我会在未来一段时间继续维护该项目，但不会做可视化，也不会发布在国内论坛。 感谢！


辛苦大佬

**Comment by bean0283** [comment]
1

**Comment by linjincs** [comment]
测试了一下，大佬的运行前面是没问题，如果连续下载5个左右，就会出现百度安全验证的页面，大佬没做过反爬处理吗？

**Comment by BoyInTheSun** [comment]
> 测试了一下，大佬的运行前面是没问题，如果连续下载5个左右，就会出现百度安全验证的页面，大佬没做过反爬处理吗？

和本issue不相关，请重提新issue
