### ISSUE TITLE
只能下载文档前两页了

### ISSUE THREAD

**Issue by Dongxinyao** [BoyInTheSun/wks#22]
只能下载文档前两页了，sad

**Comment by BoyInTheSun** [comment]
我已经发现该问题。目前我忙于备考，几月过后我会排查更新。

**Comment by JH6588** [comment]
解决了吗？ 百度文库 下多了 会封号吗

**Comment by BoyInTheSun** [comment]
> 解决了吗？ 百度文库 下多了 会封号吗

我会在近期修复。至于封号与否，我没有大批量尝试过，不知道相关规则。我非常不建议大批量爬取，因为cookie是基于账号的，有一定风险
