### ISSUE TITLE
File "json2pdf.py", line 49, in save_pdf KeyError: 'r'

### ISSUE THREAD

**Issue by smx576** [BoyInTheSun/wks#6]
大佬，有空的时候帮忙看看以下问题
这个文档下载报错
https://wenku.baidu.com/view/23160dd47a3e0912a21614791711cc7931b778be.html?fr=income4-doc-searchStart generating pdf...
|=====>--------------------------------------------| 1 / 8 (12.50%)Traceback (most recent call last):
  File "main.py", line 265, in <module>
  File "json2pdf.py", line 49, in save_pdf
KeyError: 'r'
[12988] Failed to execute script 'main' due to unhandled exception!
还有就是一些VIP文档下载也会出现问题
https://wenku.baidu.com/view/4f8550b065ce050877321306.html?fr=income3-doc-search
Do NOT support this document. File type: word

**Comment by BoyInTheSun** [comment]
未能复现[https://wenku.baidu.com/view/4f8550b065ce050877321306.html](https://wenku.baidu.com/view/4f8550b065ce050877321306.html?fr=income3-doc-search)出现的问题
请新开issues，上传临时文件夹。
