### ISSUE TITLE
Do NOT support this document. File type: word

### ISSUE THREAD

**Issue by smx576** [BoyInTheSun/wks#7]
问题链接：
https://wenku.baidu.com/view/4f8550b065ce050877321306.html?fr=income3-doc-search
临时文件链接：
https://wwt.lanzouy.com/iRWBn035ytuh

**Comment by BoyInTheSun** [comment]
从临时文件来看，确实和我这里下载结果不一样，提供的pagedata不含任何文档内容信息。
方便的话可以帮忙测试一下，浏览器控制台打开网络栏，刷新，有无https://wenku.baidu.com/ndocview/readerinfo 的请求，若有的话把完整请求参数和响应结果告诉我，谢谢

**Comment by smx576** [comment]
没有你要请求，我给你录个屏，只有这些
https://wwt.lanzouy.com/iXVOi03669yj



> 从临时文件来看，确实和我这里下载结果不一样，提供的pagedata不含任何文档内容信息。 方便的话可以帮忙测试一下，浏览器控制台打开网络栏，刷新，有无https://wenku.baidu.com/ndocview/readerinfo 的请求，若有的话把完整请求参数和响应结果告诉我，谢谢

**Comment by smx576** [comment]
> 从临时文件来看，确实和我这里下载结果不一样，提供的pagedata不含任何文档内容信息。 方便的话可以帮忙测试一下，浏览器控制台打开网络栏，刷新，有无https://wenku.baidu.com/ndocview/readerinfo 的请求，若有的话把完整请求参数和响应结果告诉我，谢谢

是号的问题，用不是会员的号下载就可以下载的了，会员的号下载就会报错

**Comment by smx576** [comment]
> 从临时文件来看，确实和我这里下载结果不一样，提供的pagedata不含任何文档内容信息。 方便的话可以帮忙测试一下，浏览器控制台打开网络栏，刷新，有无https://wenku.baidu.com/ndocview/readerinfo 的请求，若有的话把完整请求参数和响应结果告诉我，谢谢

刚刚用普通账号测试就可以下载了，可以把这个问题删除了

**Comment by BoyInTheSun** [comment]
好的，了解了，感谢！
我发现目前来看，用普通账号时，大部分不能完整查看的文档，用该项目却可以完整下载，说明仅仅是在前端做了限制。我会在未来支持对于会员账号的支持。
