### ISSUE TITLE
错误报告？if item.get('r'): KeyError: 'r'

### ISSUE THREAD

**Issue by Marches7** [BoyInTheSun/wks#9]
File "main.py", line 265, in <module>
    save_pdf(temp_dir, pagenums[i])
  File "json2pdf.py", line 49, in save_pdf
    if item.get('r'):
KeyError: 'r'
[57264] Failed to execute script 'main' due to unhandled exception!
之前下载文档都正常，今天下载一个文档报了这个错误该怎么解决？

**Comment by BoyInTheSun** [comment]
这个报错给我看傻了，请问python版本多少？

**Comment by BoyInTheSun** [comment]
之前确有KeyError: 'r'的问题，已经解决了。
https://github.com/BoyInTheSun/wks/commit/724fb5702bb6747895a7aaa63cfa941acd12418a
但从你的报错来看，这是一个新的问题，猜测你的python至少在3.7之前，因为我也不了解dict.get()的源码是何时更改的

**Comment by Marches7** [comment]
不是哦，我的python版本是3.9.7。后来我看了以下那篇文章后半页面需要vip才能展开浏览，怀疑是这个原因？

**Comment by BoyInTheSun** [comment]
和vip无关。
item是Dict()类，如果item不存在key'r'，那么item.get('r')的返回值应为None。
请确认是否更改过python源码

**Comment by wbhinspector** [comment]
> 和vip无关。 item是Dict()类，如果item不存在key'r'，那么item.get('r')的返回值应为None。 请确认是否更改过python源码

ecafc4a4bf6=1650171018,1650526965,1650689040,1651450803; Hm_lpvt_d8bfb560f8d03bbefc9bdecafc4a4bf6=1651451899' -t
Download from https://wenku.baidu.com/view/d251e0305a0102020740be1e650e52ea5518cef4.html
Download HTML...Success.
Parse HTML...Success.
title:  初中数学概率计算题解题技巧
Found pdf file, prepare for download...Success.
page:  1-2
Start downloading font(s)...
|=================================================>| 2 / 2 (100.00%)
Start downloading json(s)...
|=================================================>| 2 / 2 (100.00%)
Start downloading png(s)...
|=================================================>| 2 / 2 (100.00%)
Start generating pdf...
|========================>-------------------------| 1 / 2 (50.00%)Traceback (most recent call last):
  File "D:\Python\Python39\mycode\baidu-wenku\main.py", line 265, in <module>
    save_pdf(temp_dir, pagenums[i])
  File "D:\Python\Python39\mycode\baidu-wenku\json2pdf.py", line 83, in save_pdf
    if item['ps'].get('_drop') and item['ps'].get('_drop') == 1:
AttributeError: 'NoneType' object has no attribute 'get'
PS D:\Python\Python39\mycode\baidu-wenku>
我也有这样的错误。源码没改过。

**Comment by BoyInTheSun** [comment]
> ecafc4a4bf6=1650171018,1650526965,1650689040,1651450803; Hm_lpvt_d8bfb560f8d03bbefc9bdecafc4a4bf6=1651451899' -t Download from https://wenku.baidu.com/view/d251e0305a0102020740be1e650e52ea5518cef4.html Download HTML...Success. Parse HTML...Success. title: 初中数学概率计算题解题技巧 Found pdf file, prepare for download...Success. page: 1-2 Start downloading font(s)... |=================================================>| 2 / 2 (100.00%) Start downloading json(s)... |=================================================>| 2 / 2 (100.00%) Start downloading png(s)... |=================================================>| 2 / 2 (100.00%) Start generating pdf... |========================>-------------------------| 1 / 2 (50.00%)Traceback (most recent call last): File "D:\Python\Python39\mycode\baidu-wenku\main.py", line 265, in save_pdf(temp_dir, pagenums[i]) File "D:\Python\Python39\mycode\baidu-wenku\json2pdf.py", line 83, in save_pdf if item['ps'].get('_drop') and item['ps'].get('_drop') == 1: AttributeError: 'NoneType' object has no attribute 'get' PS D:\Python\Python39\mycode\baidu-wenku> 我也有这样的错误。源码没改过。

已经在最新的源码中[commit 377f5e7](https://github.com/BoyInTheSun/wks/commit/377f5e7143536078916cacc78ee941e8a5459e2d)修复该问题，请`git pull`。这并非相同问题。

**Comment by ahjdfeifei** [comment]
有哪位好心的大哥 有见过这个程序的使用教程吗  我刚刚入门  很多参数不知道在哪里填写?

**Comment by BoyInTheSun** [comment]
该报错应该是个例。如果仍能复现，请重开该issue
